{{- if .Values.secrets.obsidian.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-obsidian
  labels:
    app.kubernetes.io/name: wiki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: secrets
spec:
  itemPath: {{ .Values.secrets.obsidian.itemPath | quote }}
{{- end }}
