// Package assets embeds the native renderer's static frontend bundle —
// hand-authored wiki.css/wiki.js plus the vendored htmx, Alpine, KaTeX,
// Mermaid, and self-hosted webfonts. The bundle is served under /_/static/
// by the wiki server (see internal/server/server.go).
//
// Source files live alongside this Go file under fonts/ and vendor/; the
// MANIFEST.txt next door tracks pinned versions + sha256 hashes for
// reproducible builds (regenerated by scripts/vendor-assets.sh).
package assets

import (
	"embed"
	"io/fs"
	"net/http"
)

// Embedded is the immutable frontend tree. Exported so tests can list
// files; production callers should use Handler().
//
//go:embed wiki.css wiki.js MANIFEST.txt fonts vendor
var Embedded embed.FS

// Handler returns an http.Handler that serves the embedded assets. Paths
// are relative to the embed root, e.g. /vendor/htmx.min.js maps to
// vendor/htmx.min.js in the FS.
//
// We use http.FileServer + http.FS so byte-range requests + Last-Modified
// work without additional plumbing. Caching headers are applied by the
// outer middleware chain.
func Handler() http.Handler {
	return http.FileServer(http.FS(Embedded))
}

// SubFS returns the embedded filesystem as fs.FS. Useful for tests that
// want to enumerate the bundle without HTTP plumbing.
func SubFS() fs.FS { return Embedded }
