package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jedwards1230/home-wiki/internal/vault"
	"github.com/spf13/cobra"
)

func newQueueCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "queue",
		Short: "List unprocessed raw sources",
		Long:  "Show raw files missing the 'ingested' frontmatter field.",
		RunE:  runQueue,
	}

	cmd.Flags().Bool("count", false, "just print the count")
	cmd.Flags().Bool("generate", false, "regenerate meta/ingest-queue.md")

	return cmd
}

func runQueue(cmd *cobra.Command, _ []string) error {
	vaultDir, _ := cmd.Root().Flags().GetString("vault")
	v := vault.New(vaultDir)

	countOnly, _ := cmd.Flags().GetBool("count")
	generate, _ := cmd.Flags().GetBool("generate")

	unprocessed, err := findUnprocessed(v)
	if err != nil {
		return err
	}

	switch {
	case countOnly:
		fmt.Printf("%d unprocessed raw source(s)\n", len(unprocessed))
	case generate:
		return generateQueueFile(v, unprocessed)
	default:
		listUnprocessed(v, unprocessed)
	}

	return nil
}

type rawFileInfo struct {
	Path      string
	Title     string
	DateAdded string
}

func findUnprocessed(v *vault.Vault) ([]rawFileInfo, error) {
	files, err := v.FindRawFiles()
	if err != nil {
		return nil, err
	}

	var result []rawFileInfo
	for _, f := range files {
		fm, err := vault.ParseFrontmatter(f)
		if err != nil {
			// Include files we can't parse as unprocessed
			rel, _ := filepath.Rel(v.Dir, f)
			result = append(result, rawFileInfo{Path: rel, Title: strings.TrimSuffix(filepath.Base(f), ".md")})
			continue
		}

		// If frontmatter is nil (no frontmatter) or missing ingested key, it's unprocessed
		if fm == nil {
			rel, _ := filepath.Rel(v.Dir, f)
			result = append(result, rawFileInfo{Path: rel, Title: strings.TrimSuffix(filepath.Base(f), ".md")})
			continue
		}

		if _, ok := fm["ingested"]; !ok {
			rel, _ := filepath.Rel(v.Dir, f)
			title := fm["title"]
			if title == "" {
				title = strings.TrimSuffix(filepath.Base(f), ".md")
			}
			result = append(result, rawFileInfo{
				Path:      rel,
				Title:     title,
				DateAdded: fm["date-added"],
			})
		}
	}

	return result, nil
}

func listUnprocessed(v *vault.Vault, items []rawFileInfo) {
	if len(items) == 0 {
		fmt.Println("All raw sources have been ingested.")
		return
	}
	for _, item := range items {
		dateStr := item.DateAdded
		if dateStr == "" {
			dateStr = "--"
		}
		fmt.Printf("%-50s  %s  %s\n", item.Path, dateStr, item.Title)
	}
}

func generateQueueFile(v *vault.Vault, items []rawFileInfo) error {
	queueFile := filepath.Join(v.Dir, "meta", "ingest-queue.md")

	// Ensure meta/ dir exists
	if err := os.MkdirAll(filepath.Dir(queueFile), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	today := time.Now().Format("2006-01-02")

	b.WriteString("---\n")
	b.WriteString("title: Ingest Queue\n")
	b.WriteString("tags:\n")
	b.WriteString("  - meta\n")
	fmt.Fprintf(&b, "date: %s\n", today)
	b.WriteString("---\n\n")
	b.WriteString("Auto-generated by `wiki-server queue --generate`. Do not edit manually.\n\n")

	if len(items) == 0 {
		b.WriteString("No unprocessed raw sources.\n")
	} else {
		b.WriteString("| File | Added | Title |\n")
		b.WriteString("|------|-------|-------|\n")
		for _, item := range items {
			dateStr := item.DateAdded
			if dateStr == "" {
				dateStr = "--"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", item.Path, dateStr, item.Title)
		}
	}

	if err := os.WriteFile(queueFile, []byte(b.String()), 0o644); err != nil {
		return err
	}

	fmt.Printf("Generated %s (%d item(s))\n", queueFile, len(items))
	return nil
}
