package service

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jedwards1230/home-wiki/internal/vault"
)

// IngestService provides raw source queue operations.
type IngestService struct {
	vault *vault.Vault
}

// NewIngestService creates an IngestService for the given vault.
func NewIngestService(v *vault.Vault) *IngestService {
	return &IngestService{vault: v}
}

// List returns all unprocessed raw source files.
func (s *IngestService) List() ([]RawFileInfo, error) {
	files, err := s.vault.FindRawFiles()
	if err != nil {
		return nil, err
	}

	var result []RawFileInfo
	for _, f := range files {
		fm, err := vault.ParseFrontmatter(f)
		if err != nil {
			rel, _ := filepath.Rel(s.vault.Dir, f)
			result = append(result, RawFileInfo{
				Path:  rel,
				Title: strings.TrimSuffix(filepath.Base(f), ".md"),
			})
			continue
		}

		if fm == nil {
			rel, _ := filepath.Rel(s.vault.Dir, f)
			result = append(result, RawFileInfo{
				Path:  rel,
				Title: strings.TrimSuffix(filepath.Base(f), ".md"),
			})
			continue
		}

		if _, ok := fm["ingested"]; !ok {
			rel, _ := filepath.Rel(s.vault.Dir, f)
			title := fm["title"]
			if title == "" {
				title = strings.TrimSuffix(filepath.Base(f), ".md")
			}
			result = append(result, RawFileInfo{
				Path:      rel,
				Title:     title,
				DateAdded: fm["date-added"],
			})
		}
	}

	return result, nil
}

// Generate regenerates meta/ingest-queue.md from unprocessed items.
func (s *IngestService) Generate() (string, int, error) {
	items, err := s.List()
	if err != nil {
		return "", 0, err
	}

	queueFile := filepath.Join(s.vault.Dir, "meta", "ingest-queue.md")

	if err := os.MkdirAll(filepath.Dir(queueFile), 0o755); err != nil {
		return "", 0, err
	}

	var b strings.Builder
	today := time.Now().Format("2006-01-02")

	b.WriteString("---\n")
	b.WriteString("title: Ingest Queue\n")
	b.WriteString("tags:\n")
	b.WriteString("  - meta\n")
	_, _ = fmt.Fprintf(&b, "date: %s\n", today)
	b.WriteString("---\n\n")
	b.WriteString("Auto-generated by `wiki-server ingest --generate`. Do not edit manually.\n\n")

	if len(items) == 0 {
		b.WriteString("No unprocessed raw sources.\n")
	} else {
		b.WriteString("| File | Added | Title |\n")
		b.WriteString("|------|-------|-------|\n")
		for _, item := range items {
			dateStr := item.DateAdded
			if dateStr == "" {
				dateStr = "--"
			}
			safeTitle := strings.ReplaceAll(item.Title, "|", "\\|")
			safeTitle = strings.ReplaceAll(safeTitle, "\n", " ")
			_, _ = fmt.Fprintf(&b, "| `%s` | %s | %s |\n", item.Path, dateStr, safeTitle)
		}
	}

	newContent := []byte(b.String())
	// Skip the write if bytes are unchanged — see DirectoryService.Generate for
	// the rationale (fsnotify feedback loop in serve mode). Only "does not
	// exist" read errors trigger a write; other read errors are surfaced.
	existing, readErr := os.ReadFile(queueFile)
	if readErr != nil && !os.IsNotExist(readErr) {
		return "", 0, readErr
	}
	if readErr == nil && bytes.Equal(existing, newContent) {
		return queueFile, len(items), nil
	}
	if err := os.WriteFile(queueFile, newContent, 0o644); err != nil {
		return "", 0, err
	}

	return queueFile, len(items), nil
}
