#!/usr/bin/env bash
# seed-vault.sh — Generate a comprehensive throwaway vault that exercises every
# rendering form, page type, wikilink/backlink, transclusion, and exclusion the
# native renderer supports. Use it for visual verification (Playwright) and for
# manual spot-checks of CSS/template/renderer changes.
#
# Idempotent: the target directory is wiped and recreated on every run, so the
# output is deterministic. It only ever touches the target dir (default
# /tmp/wiki-test-vault) — zero side effects elsewhere.
#
# Coverage map (one feature per page where practical):
#   index.md                     root folder-index → "/"  + intro callout
#   getting-started.md           core GFM: headings, emphasis, lists, task
#                                lists, tables, code, blockquote, hr, footnotes,
#                                definition lists, emoji, links, images
#   rendering/index.md           nested folder-index → "/rendering/"
#   rendering/callouts.md        all 13 callout kinds + foldable (+/-)
#   rendering/code-blocks.md     syntax highlighting across several languages
#   rendering/math.md            inline $x$ + block $$…$$ (KaTeX)
#   rendering/diagrams.md        ```mermaid flowchart + sequence
#   rendering/obsidian.md        ==highlight==, %%comment%%, ^block-id, #tags
#   wikilinks/source.md          [[target]], [[target|alias]], [[target#h]],
#                                [[target#^block]] — drives backlinks on target
#   wikilinks/target.md          headings + ^block-id; links back to source
#   transclusion/a→b→c→d.md      ![[…]] chain to exercise the depth-3 limit
#   transclusion/partial.md      ![[target#heading]] + ![[target#^block]]
#   raw/*.{txt,yaml,sh}          native source files + /raw directory listing
#   private/secret.md            MUST be excluded from listings (negative test)
#
# Shared tags (#demo #rendering #reference) span multiple pages so tag-listing
# pages have more than one entry.

set -euo pipefail

# --- CLI -------------------------------------------------------------------
# Usage: scripts/seed-vault.sh [TARGET_DIR]   (default: /tmp/wiki-test-vault)
VAULT="${1:-/tmp/wiki-test-vault}"

if [[ "$VAULT" != /* && "$VAULT" != ./* ]]; then
	VAULT="./$VAULT" # guard against an accidental `rm -rf` on a bare name
fi

# --- helpers ---------------------------------------------------------------
# page <relative/path.md> reads file body from stdin and writes it under $VAULT,
# creating parent directories as needed.
page() {
	local dest="$VAULT/$1"
	mkdir -p "$(dirname "$dest")"
	cat >"$dest"
}

# --- (re)create the vault --------------------------------------------------
rm -rf "$VAULT"
mkdir -p "$VAULT"

# ---------------------------------------------------------------------------
# Root index — folder index served at "/"
# ---------------------------------------------------------------------------
page index.md <<'EOF'
---
title: Test Vault
description: A throwaway vault that exercises every renderer feature.
tags: [demo]
date: 2026-01-01
maintainer: seed-vault.sh
status: fixture
homepage: https://github.com/jedwards1230/my-wiki
---

# Test Vault

This vault is generated by `scripts/seed-vault.sh` to exercise the native
renderer end to end. Start here, then walk the sections.

> [!info] Visual verification fixture
> Every page targets a specific rendering feature so screenshots cover the
> whole surface in light and dark mode.

## Sections

- [[getting-started]] — core Markdown / GFM
- [[rendering/index|Rendering reference]] — callouts, code, math, diagrams
- [[wikilinks/source]] and [[wikilinks/target]] — links + backlinks
- [[transclusion/a]] — embed/transclusion chain
- See `/raw/` for the native source-file listing

The frontmatter above also drives the **properties table** (maintainer,
status, homepage) — the last is auto-linked because it is a URL.
EOF

# ---------------------------------------------------------------------------
# Core Markdown / GFM
# ---------------------------------------------------------------------------
page getting-started.md <<'EOF'
---
title: Getting Started
tags: [demo, reference]
date: 2026-01-02
aliases: [intro, basics]
---

# Getting Started

Core Markdown and GitHub-Flavored Markdown in one page.

## Text & emphasis

Plain, **bold**, *italic*, ***bold italic***, ~~strikethrough~~, `inline code`,
and an autolink: https://example.com.

## Lists

- Unordered item
  - Nested item
    - Deeper item
- Back to top level

1. Ordered one
2. Ordered two
   1. Nested ordered

### Task list

- [x] Completed task
- [ ] Open task
- [ ] Another open task

## Table

| Feature   | Status | Notes                |
| :-------- | :----: | -------------------: |
| Tables    |   ✅   | alignment: L, C, R   |
| Callouts  |   ✅   | 13 kinds             |
| Math      |   ✅   | KaTeX                |

## Blockquote & rule

> A blockquote without a callout marker stays a plain blockquote.

---

## Footnotes & definition lists

Here is a statement with a footnote.[^1]

Term
: Definition of the term.

Another term
: Its definition.

[^1]: The footnote body renders at the bottom of the article.

## Emoji & links

Emoji shortcodes render too: :rocket: :sparkles: :white_check_mark:.

An external [labeled link](https://example.com) and an internal
[[rendering/index|rendering reference]].
EOF

# ---------------------------------------------------------------------------
# Rendering section — folder index
# ---------------------------------------------------------------------------
page rendering/index.md <<'EOF'
---
title: Rendering Reference
tags: [demo, rendering]
date: 2026-01-03
---

# Rendering Reference

Each page below isolates one rendering feature.

- [[rendering/callouts]] — all callout kinds
- [[rendering/code-blocks]] — syntax highlighting
- [[rendering/math]] — KaTeX
- [[rendering/diagrams]] — Mermaid
- [[rendering/obsidian]] — Obsidian-flavored extras
EOF

# ---------------------------------------------------------------------------
# Callouts — all 13 kinds + foldable
# ---------------------------------------------------------------------------
page rendering/callouts.md <<'EOF'
---
title: Callouts
tags: [rendering]
date: 2026-01-04
---

# Callouts

All 13 built-in kinds, plus foldable variants.

> [!note] Note
> Body text for a note callout.

> [!info] Info
> Informational aside.

> [!tip] Tip
> A helpful tip.

> [!warning] Warning
> Something to be careful about.

> [!danger] Danger
> A dangerous operation.

> [!example] Example
> An illustrative example.

> [!quote] Quote
> A quoted passage.

> [!abstract] Abstract
> A short abstract / summary.

> [!todo] Todo
> A to-do item.

> [!success] Success
> A success / done state.

> [!question] Question
> An open question.

> [!failure] Failure
> A failure state.

> [!bug] Bug
> A known bug.

## Foldable

> [!tip]+ Expanded by default
> The `+` marker starts this callout open.

> [!warning]- Collapsed by default
> The `-` marker starts this callout collapsed.

## Untitled

> [!info]
> A callout with no title falls back to the kind name.
EOF

# ---------------------------------------------------------------------------
# Code blocks — syntax highlighting (Chroma)
# ---------------------------------------------------------------------------
page rendering/code-blocks.md <<'EOF'
---
title: Code Blocks
tags: [rendering, reference]
date: 2026-01-05
---

# Code Blocks

Fenced blocks across languages exercise the Chroma highlighter (light "github",
dark "github-dark") and the copy button.

```go
package main

import "fmt"

func main() {
	fmt.Println("hello, wiki")
}
```

```python
def greet(name: str) -> str:
    return f"hello, {name}"
```

```typescript
const greet = (name: string): string => `hello, ${name}`;
```

```bash
#!/usr/bin/env bash
set -euo pipefail
echo "rendered"
```

```json
{ "ok": true, "items": [1, 2, 3] }
```

```sql
SELECT id, title FROM pages WHERE tag = 'rendering' ORDER BY id;
```

A block with no language is plain `<pre>`:

```
no language → no highlighting
```
EOF

# ---------------------------------------------------------------------------
# Math — KaTeX (inline + block)
# ---------------------------------------------------------------------------
page rendering/math.md <<'EOF'
---
title: Math
tags: [rendering]
date: 2026-01-06
---

# Math

Inline math like $e^{i\pi} + 1 = 0$ renders with KaTeX. So does a block:

$$
\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}
$$

A matrix:

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$
EOF

# ---------------------------------------------------------------------------
# Diagrams — Mermaid (lazy-loaded client-side)
# ---------------------------------------------------------------------------
page rendering/diagrams.md <<'EOF'
---
title: Diagrams
tags: [rendering]
date: 2026-01-07
---

# Diagrams

Mermaid blocks render client-side (`wiki.js` lazy-loads `mermaid.min.js`).

```mermaid
flowchart LR
    A[Request] --> B{Cached?}
    B -- yes --> C[Serve snapshot]
    B -- no --> D[Render] --> C
```

```mermaid
sequenceDiagram
    participant U as User
    participant S as Server
    U->>S: GET /page/
    S-->>U: rendered HTML
```
EOF

# ---------------------------------------------------------------------------
# Obsidian extras — highlight, comment, block-id, inline tags
# ---------------------------------------------------------------------------
page rendering/obsidian.md <<'EOF'
---
title: Obsidian Extras
tags: [rendering, reference]
date: 2026-01-08
---

# Obsidian Extras

Inline ==highlighted text== renders with a mark background.

There is a hidden comment after this sentence. %%this comment must not render%%

This paragraph carries a block id so it can be transcluded. ^intro-block

Inline tags are recognized too: #demo #rendering — they link to tag pages.
EOF

# ---------------------------------------------------------------------------
# Wikilinks + backlinks (source ↔ target)
# ---------------------------------------------------------------------------
page wikilinks/source.md <<'EOF'
---
title: Wikilink Source
tags: [demo]
date: 2026-01-09
---

# Wikilink Source

Every wikilink shape pointing at [[wikilinks/target]]:

- Plain: [[wikilinks/target]]
- Aliased: [[wikilinks/target|a friendly alias]]
- To a heading: [[wikilinks/target#Section Two]]
- To a block: [[wikilinks/target#^anchor]]
- Unresolved (should render as a broken/empty link): [[does-not-exist]]

Because this page links to the target, the target's **backlinks** panel should
list this page.
EOF

page wikilinks/target.md <<'EOF'
---
title: Wikilink Target
tags: [demo, reference]
date: 2026-01-10
---

# Wikilink Target

## Section One

Content for the first section.

## Section Two

Content for the second section — linked via `#Section Two`.

This sentence has a block anchor for `#^anchor` links. ^anchor

See also [[wikilinks/source]] (creates a backlink in both directions).
EOF

# ---------------------------------------------------------------------------
# Transclusion chain a → b → c → d (depth limit is 3)
# ---------------------------------------------------------------------------
page transclusion/a.md <<'EOF'
---
title: Transclude A
tags: [demo]
date: 2026-01-11
---

# Transclude A

A embeds B:

![[transclusion/b]]
EOF

page transclusion/b.md <<'EOF'
---
title: Transclude B
date: 2026-01-11
---

# Transclude B

B embeds C:

![[transclusion/c]]
EOF

page transclusion/c.md <<'EOF'
---
title: Transclude C
date: 2026-01-11
---

# Transclude C

C embeds D (this is where the depth-3 limit kicks in):

![[transclusion/d]]
EOF

page transclusion/d.md <<'EOF'
---
title: Transclude D
date: 2026-01-11
---

# Transclude D

Leaf of the chain — nothing embedded here.
EOF

page transclusion/partial.md <<'EOF'
---
title: Partial Transclusion
tags: [reference]
date: 2026-01-12
---

# Partial Transclusion

Embed just a section:

![[wikilinks/target#Section Two]]

Embed just a block:

![[rendering/obsidian#^intro-block]]
EOF

# ---------------------------------------------------------------------------
# raw/ — native source files (served at /raw/ with a directory listing)
# ---------------------------------------------------------------------------
page raw/example.txt <<'EOF'
This is a raw text file served natively at /raw/example.txt.
It is NOT rendered as markdown and is excluded from the page directory,
but it IS a valid wikilink target.
EOF

page raw/config.yaml <<'EOF'
# raw YAML, served verbatim
server:
  port: 8080
  vault: /path/to/vault
features:
  search: true
  mcp: true
EOF

page raw/script.sh <<'EOF'
#!/usr/bin/env bash
# raw shell script served verbatim under /raw/
echo "not executed — just served as source"
EOF

# ---------------------------------------------------------------------------
# private/ — MUST be excluded from sync and page listings (negative test)
# ---------------------------------------------------------------------------
page private/secret.md <<'EOF'
---
title: Secret
---

# Secret

If this page shows up in the explorer, search, or any listing, exclusion is
broken. It should be invisible to the rendered site.
EOF

# --- done ------------------------------------------------------------------
file_count="$(find "$VAULT" -type f | wc -l | tr -d ' ')"
echo "Seeded $file_count files into: $VAULT"
echo
echo "Serve it (auth fails closed, so the opt-out is required):"
echo "  WIKI_AUTH_DISABLED=true ./wiki-server serve --vault $VAULT --port 9876"
echo
echo "Then verify with Playwright (firefox), e.g. http://localhost:9876/"
