{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: wiki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wiki
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.interval | default "30s" }}
{{- end }}
